### ISSUE TITLE
space required after colon in secret.yaml file

### ISSUE THREAD

**Issue by jiata** [Azure/thunderbolt#103]
it seems like yaml requires a space after the colon.

for example, this works:
```
batchaccountname: myaccount
```
but this doesn't:
```
batchaccountname:myaccount
```

Possibly not a bug, but is this the expected behavior? Or are we just parsing so that it requires the space?

**Comment by timotheeguerin** [comment]
pretty sure this is yaml specs https://stackoverflow.com/questions/42124227/why-does-the-yaml-spec-mandate-a-space-after-the-colon

**Comment by jiata** [comment]
got it. Is there a good way to handle that error? I was confused by the error msg.
<img width="820" alt="secrets_config" src="https://user-images.githubusercontent.com/16616215/30845188-3ff86c7e-a260-11e7-9ca1-4e6896a651ed.png">

**Comment by timotheeguerin** [comment]
yeah not sure if there is anything we can do for this error. But I feel like editor syntax highlighting should show the user something is wrong. See with vscode:
![image](https://user-images.githubusercontent.com/1031227/30845267-7b5c0186-a247-11e7-8535-f967892b28c6.png)

**Comment by jiata** [comment]
yeah, vscode is nice. i was just on a new vm and wanted to get something up and running quickly, so i was just editing in the default text editor program (notes i think?)

mmm.. yeah not sure, maybe this is something we call out in our documentation. I feel like this may cause problem for lots of non-yaml users (already had one other than myself!)

**Comment by jafreck** [comment]
We can catch the yaml error and tell the user something like "There is an issue with your secrets.yaml configuration near line 6 column 20". We probably won't be able to get much more specific than that.

**Comment by jiata** [comment]
cool. yeah, @jafreck thats better than nothing imo. + some documentation.
