### ISSUE TITLE
azb spark cluster submit cannot reference files that are not in working directory

### ISSUE THREAD

**Issue by jiata** [Azure/thunderbolt#105]
This doesn't work (absolute path):
`azb spark cluster submit ... /Users/jiata/code/thunderbolt/examples/src/main/python/pi.py 100`

This also doesn't work (relative path):
`azb spark cluster submit ... ../another-thunderbolt/examples/src/main/python/pi.py 100`

This works (we we'd expect):
`azb spark cluster submit ... /examples/src/main/python/pi.py 100`

**Comment by jafreck** [comment]
I was able to submit a job successfully using an absolute path on Windows so that part of the issue may be limited to linux and osx clients.
